name: Trigger on Merge to Specific Branches

on:
  push:
    branches:
      - local-dev
      - local-stg
      - cloud-stg
      - cloud-prod

jobs:
  run-on-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Example step
        run: echo "This workflow runs on merge to specific branches."